version: '3.9'

services:
  mongodb:
    image: mongo:7.0.12
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - ./mongo_data:/data/db
    ports:
      - 27017:27017
